export interface Engine {
  slug: string
  code: string
  name: string
  description: string
  url: string
  checklist: string[]
}

export const ENGINES: Engine[] = [
  {
    slug: 'hivephoto',
    code: 'HPHT',
    name: 'HivePhoto',
    description: 'AI-powered private photo library with smart search, face recognition, and duplicate detection.',
    url: 'https://hivephoto.hive.baby',
    checklist: [
      'Sign up and confirm email arrives in under 2 minutes',
      'Upload 3 photos from different dates',
      'Upload the same photo twice — does duplicate detection catch it?',
      'Try the search: "show me photos with people"',
      'Check the GPS map view accuracy',
      'Try the search: "show me happy photos"',
      'Rate the AI analysis accuracy for one photo',
      'Test face grouping — are faces correctly grouped?',
      'Download a photo at original quality',
      'Test the full UI on mobile layout',
    ],
  },
  {
    slug: 'ud-translate',
    code: 'UDTR',
    name: 'UD Translate',
    description: 'Translate Universal Documents into 35+ languages while preserving structure, seal, and formatting.',
    url: 'https://utilities.hive.baby/translate',
    checklist: [
      'Upload any .uds file',
      'Translate to Persian — does output use Farsi script?',
      'Translate to Hindi — does output use Devanagari script?',
      'Translate to Arabic — is text right-to-left?',
      'Translate to Chinese — are characters used (not romanised)?',
      'Translate to Japanese — are kanji/hiragana used?',
      'Open translated file in UD Reader — does it render correctly?',
      'Language switcher works in Reader?',
      'Translate a long document — no timeout under 60 seconds?',
      'Translate an already-translated document — handles gracefully?',
    ],
  },
  {
    slug: 'ud-pharmacy',
    code: 'UDPH',
    name: 'UD Pharmacy',
    description: 'Generate tamper-evident digital prescriptions as sealed Universal Documents.',
    url: 'https://utilities.hive.baby/pharmacy',
    checklist: [
      'Fill all fields and generate a prescription',
      'Download the .uds file',
      'Open in UD Reader — does it look like a real prescription?',
      'Check the expiry date is approximately 30 days out',
      'Try an invalid medication name — is there a helpful error?',
      'Open in UD Validator — does it PASS validation?',
      'Test the full form on mobile',
      'Check the seal status in Reader',
      'Try revoking the prescription',
      'Verify the hash is consistent between downloads',
    ],
  },
  {
    slug: 'ud-converter',
    code: 'UDCV',
    name: 'UD Converter',
    description: 'Convert PDFs, Word docs, and text files into Universal Document format.',
    url: 'https://converter.hive.baby',
    checklist: [
      'Convert a PDF with multiple sections',
      'Convert a Word document (.docx)',
      'Convert a plain text file',
      'Check that headings are preserved as heading blocks',
      'Check that paragraph structure is maintained',
      'Open converted file in UD Reader',
      'Validate converted file in UD Validator',
      'Try a scanned PDF (image-only) — how does it handle it?',
      'Test a very large document (10+ pages)',
      'Download and re-upload the same file — consistent output?',
    ],
  },
  {
    slug: 'ud-reader',
    code: 'UDRDR',
    name: 'UD Reader',
    description: 'Read and verify sealed Universal Documents with full audit trail and seal verification.',
    url: 'https://ud.hive.baby',
    checklist: [
      'Open a .uds file — does the seal status show correctly?',
      'Open a .udr file — does draft status show correctly?',
      'Switch language on a translated document',
      'Switch clarity layers if available',
      'Check chain of custody shows correctly',
      'Verify seal hash for a sealed document',
      'Open a revoked document — does it flag as revoked?',
      'Test on mobile — is layout correct?',
      'Print a document — does formatting hold?',
      'Open an invalid file — clear error message?',
    ],
  },
  {
    slug: 'ud-validator',
    code: 'UDVL',
    name: 'UD Validator',
    description: 'Validate Universal Documents against the full UDS schema with line-by-line error reporting.',
    url: 'https://utilities.hive.baby/validator',
    checklist: [
      'Validate a known-good .uds file — reports PASS',
      'Validate a known-bad .uds file — reports FAIL with specifics',
      'Upload a non-JSON file — clear error message?',
      'Upload an empty file — handled gracefully?',
      'Check that all error messages are understandable',
      'Validate a translated document',
      'Validate a sealed document — seal check works?',
      'Validate a revoked document — flagged?',
      'Test on mobile',
      'Try drag-and-drop upload',
    ],
  },
  {
    slug: 'ud-signer',
    code: 'UDSN',
    name: 'UD Signer',
    description: 'Digitally sign Universal Documents with cryptographic proof and chain of custody.',
    url: 'https://signer.hive.baby',
    checklist: [
      'Sign a .udr file — converts to .uds correctly?',
      'Check the seal hash is correct after signing',
      'Verify a signed document in UD Reader',
      'Sign the same file twice — second signing handled?',
      'Sign with a custom signer name',
      'Check chain of custody includes the signing event',
      'Download the signed file and re-verify',
      'Try signing a .uds file (already sealed)',
      'Test on mobile',
      'Sign a large document — no timeout?',
    ],
  },
  {
    slug: 'ud-contract-intelligence',
    code: 'UDCI',
    name: 'UD Contract Intelligence',
    description: 'AI-powered contract analysis that extracts key terms, obligations, and risks as a sealed UD.',
    url: 'https://utilities.hive.baby/contract-intelligence',
    checklist: [
      'Upload a contract PDF or text',
      'Check that key clauses are extracted correctly',
      'Check that obligations are listed clearly',
      'Check that risks are flagged',
      'Open output in UD Reader',
      'Validate output in UD Validator',
      'Try a non-contract document — graceful handling?',
      'Test with a very long contract (10+ pages)',
      'Check AI summary accuracy',
      'Download and re-open — consistent output?',
    ],
  },
  {
    slug: 'ud-clinical-summary',
    code: 'UDCS',
    name: 'UD Clinical Summary',
    description: 'Convert clinical notes into structured, sealed patient summary documents.',
    url: 'https://utilities.hive.baby/clinical-summary',
    checklist: [
      'Paste a set of clinical notes and generate',
      'Check SOAP format is followed',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with complex multi-problem notes',
      'Test with minimal notes (1-2 sentences)',
      'Check that medical disclaimer is present',
      'Check metadata fields are populated',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-document-intelligence',
    code: 'UDDI',
    name: 'UD Document Intelligence',
    description: 'Extract structured data from any document and output as a validated Universal Document.',
    url: 'https://utilities.hive.baby/document-intelligence',
    checklist: [
      'Upload a form or structured document',
      'Check that fields are extracted correctly',
      'Check that tables are preserved',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Try a scanned document',
      'Try a handwritten note (if supported)',
      'Test with multilingual content',
      'Check AI accuracy rating',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-summarise',
    code: 'UDSUM',
    name: 'UD Summarise',
    description: 'AI-powered document summarisation that outputs a sealed summary as a Universal Document.',
    url: 'https://utilities.hive.baby/summarise',
    checklist: [
      'Upload a long document and summarise',
      'Check summary length is appropriate',
      'Check key points are captured',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with a very short document',
      'Test with a document in another language',
      'Check metadata includes source reference',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-classify',
    code: 'UDCLS',
    name: 'UD Classify',
    description: 'Automatically classify documents by type, sensitivity, and audience.',
    url: 'https://utilities.hive.baby/classify',
    checklist: [
      'Upload a medical document — classified correctly?',
      'Upload a legal document — classified correctly?',
      'Upload a financial document — classified correctly?',
      'Upload a personal letter — classified correctly?',
      'Check sensitivity level is appropriate',
      'Check audience classification makes sense',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with an ambiguous document',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-emr-export',
    code: 'UDEMR',
    name: 'UD EMR Export',
    description: 'Convert HL7, FHIR, C-CDA, and clinical records into sealed patient documents.',
    url: 'https://utilities.hive.baby/emr-export',
    checklist: [
      'Upload a sample HL7 file',
      'Upload a FHIR JSON record',
      'Upload a plain-text clinical note',
      'Check patient summary is accurate',
      'Check diagnoses are listed correctly',
      'Check medications are formatted correctly',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Check medical disclaimer is present',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-accessibility-check',
    code: 'UDAC',
    name: 'UD Accessibility Check',
    description: 'Audit Universal Documents for accessibility compliance and generate a remediation report.',
    url: 'https://utilities.hive.baby/accessibility-check',
    checklist: [
      'Upload a document and run accessibility check',
      'Check that issues are described clearly',
      'Check that remediation suggestions are actionable',
      'Test with a well-structured document — should have few issues',
      'Test with a poorly structured document — should flag many issues',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Check that severity levels are assigned',
      'Test on mobile',
      'Download report and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-watermark',
    code: 'UDWM',
    name: 'UD Watermark',
    description: 'Apply invisible cryptographic watermarks to Universal Documents for tracking and provenance.',
    url: 'https://utilities.hive.baby/watermark',
    checklist: [
      'Apply a watermark to a .uds file',
      'Check watermark metadata is embedded',
      'Open watermarked file in UD Reader',
      'Validate in UD Validator',
      'Try applying watermark twice — handled correctly?',
      'Check chain of custody updated',
      'Verify watermark data is readable from metadata',
      'Test with a large document',
      'Test on mobile',
      'Download and re-verify — consistent?',
    ],
  },
  {
    slug: 'ud-compare',
    code: 'UDCMP',
    name: 'UD Compare',
    description: 'Compare two Universal Documents and generate a diff report showing all changes.',
    url: 'https://utilities.hive.baby/compare',
    checklist: [
      'Compare two identical documents — reports no changes',
      'Compare two similar documents — differences shown clearly',
      'Compare original and translated versions',
      'Check that added blocks are highlighted',
      'Check that deleted blocks are highlighted',
      'Check that modified blocks show before/after',
      'Open diff report in UD Reader',
      'Validate diff report in UD Validator',
      'Test with large documents',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-merge',
    code: 'UDMRG',
    name: 'UD Merge',
    description: 'Merge multiple Universal Documents into a single consolidated document.',
    url: 'https://utilities.hive.baby/merge',
    checklist: [
      'Merge two documents — output is a combined document',
      'Check that all blocks from both documents appear',
      'Check that metadata is merged correctly',
      'Open merged file in UD Reader',
      'Validate in UD Validator',
      'Merge three or more documents',
      'Merge documents in different languages',
      'Check chain of custody includes merge event',
      'Test with large documents',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-ocr',
    code: 'UDOCR',
    name: 'UD OCR',
    description: 'Extract text from scanned documents and images and output as Universal Documents.',
    url: 'https://utilities.hive.baby/ocr',
    checklist: [
      'Upload a scanned PDF — text extracted correctly?',
      'Upload a photo of a document — text extracted?',
      'Check accuracy of extracted text',
      'Check that layout is preserved where possible',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Try a low-quality scan — graceful handling?',
      'Try a multilingual document',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },
]

export function getEngineBySlug(slug: string): Engine | undefined {
  return ENGINES.find(e => e.slug === slug)
}

export function getEngineByCode(code: string): Engine | undefined {
  return ENGINES.find(e => e.code === code)
}
