export interface Engine {
  slug: string
  code: string
  name: string
  description: string
  url: string
  checklist: string[]
}

export const ENGINES: Engine[] = [
  // ── UD Ecosystem ──────────────────────────────────────────────
  {
    slug: 'ud-reader',
    code: 'UDRDR',
    name: 'UD Reader',
    description: 'Read and verify sealed Universal Documents with full audit trail and seal verification.',
    url: 'https://ud.hive.baby',
    checklist: [
      'Open a .uds file — does the seal status show correctly?',
      'Open a .udr file — does draft status show correctly?',
      'Switch language on a translated document',
      'Switch clarity layers if available',
      'Check chain of custody shows correctly',
      'Verify seal hash for a sealed document',
      'Open a revoked document — does it flag as revoked?',
      'Test on mobile — is layout correct?',
      'Print a document — does formatting hold?',
      'Open an invalid file — clear error message?',
    ],
  },
  {
    slug: 'ud-converter',
    code: 'UDCV',
    name: 'UD Converter',
    description: 'Convert PDFs, Word docs, and text files into Universal Document format.',
    url: 'https://converter.hive.baby',
    checklist: [
      'Convert a PDF with multiple sections',
      'Convert a Word document (.docx)',
      'Convert a plain text file',
      'Check that headings are preserved as heading blocks',
      'Check that paragraph structure is maintained',
      'Open converted file in UD Reader',
      'Validate converted file in UD Validator',
      'Try a scanned PDF (image-only) — how does it handle it?',
      'Test a very large document (10+ pages)',
      'Download and re-upload the same file — consistent output?',
    ],
  },
  {
    slug: 'ud-creator',
    code: 'UDCRT',
    name: 'UD Creator',
    description: 'Create Universal Documents from scratch with a structured editor and instant sealing.',
    url: 'https://creator.hive.baby',
    checklist: [
      'Create a new document with a title and multiple sections',
      'Add a paragraph block and a heading block',
      'Save as .udr (draft) — file downloads correctly?',
      'Seal the document — outputs .uds correctly?',
      'Open sealed file in UD Reader — renders correctly?',
      'Validate sealed file in UD Validator — PASS?',
      'Add metadata fields (author, date, category)',
      'Try adding all supported block types',
      'Test on mobile — editor usable?',
      'Create and seal two documents — hashes are different?',
    ],
  },
  {
    slug: 'ud-validator',
    code: 'UDVL',
    name: 'UD Validator',
    description: 'Validate Universal Documents against the full UDS schema with line-by-line error reporting.',
    url: 'https://utilities.hive.baby/validator',
    checklist: [
      'Validate a known-good .uds file — reports PASS',
      'Validate a known-bad .uds file — reports FAIL with specifics',
      'Upload a non-JSON file — clear error message?',
      'Upload an empty file — handled gracefully?',
      'Check that all error messages are understandable',
      'Validate a translated document',
      'Validate a sealed document — seal check works?',
      'Validate a revoked document — flagged?',
      'Test on mobile',
      'Try drag-and-drop upload',
    ],
  },
  {
    slug: 'ud-signer',
    code: 'UDSN',
    name: 'UD Signer',
    description: 'Digitally sign Universal Documents with cryptographic proof and chain of custody.',
    url: 'https://signer.hive.baby',
    checklist: [
      'Sign a .udr file — converts to .uds correctly?',
      'Check the seal hash is correct after signing',
      'Verify a signed document in UD Reader',
      'Sign the same file twice — second signing handled?',
      'Sign with a custom signer name',
      'Check chain of custody includes the signing event',
      'Download the signed file and re-verify',
      'Try signing a .uds file (already sealed)',
      'Test on mobile',
      'Sign a large document — no timeout?',
    ],
  },
  {
    slug: 'ud-translate',
    code: 'UDTR',
    name: 'UD Translate',
    description: 'Translate Universal Documents into 35+ languages while preserving structure, seal, and formatting.',
    url: 'https://utilities.hive.baby/translate',
    checklist: [
      'Upload any .uds file',
      'Translate to Persian — does output use Farsi script?',
      'Translate to Hindi — does output use Devanagari script?',
      'Translate to Arabic — is text right-to-left?',
      'Translate to Chinese — are characters used (not romanised)?',
      'Translate to Japanese — are kanji/hiragana used?',
      'Open translated file in UD Reader — does it render correctly?',
      'Language switcher works in Reader?',
      'Translate a long document — no timeout under 60 seconds?',
      'Translate an already-translated document — handles gracefully?',
    ],
  },
  {
    slug: 'ud-pharmacy',
    code: 'UDPH',
    name: 'UD Pharmacy',
    description: 'Generate tamper-evident digital prescriptions as sealed Universal Documents.',
    url: 'https://utilities.hive.baby/pharmacy',
    checklist: [
      'Fill all fields and generate a prescription',
      'Download the .uds file',
      'Open in UD Reader — does it look like a real prescription?',
      'Check the expiry date is approximately 30 days out',
      'Try an invalid medication name — is there a helpful error?',
      'Open in UD Validator — does it PASS validation?',
      'Test the full form on mobile',
      'Check the seal status in Reader',
      'Try revoking the prescription',
      'Verify the hash is consistent between downloads',
    ],
  },
  {
    slug: 'ud-contract-intelligence',
    code: 'UDCI',
    name: 'UD Contract Intelligence',
    description: 'AI-powered contract analysis that extracts key terms, obligations, and risks as a sealed UD.',
    url: 'https://utilities.hive.baby/contract-intelligence',
    checklist: [
      'Upload a contract PDF or text',
      'Check that key clauses are extracted correctly',
      'Check that obligations are listed clearly',
      'Check that risks are flagged',
      'Open output in UD Reader',
      'Validate output in UD Validator',
      'Try a non-contract document — graceful handling?',
      'Test with a very long contract (10+ pages)',
      'Check AI summary accuracy',
      'Download and re-open — consistent output?',
    ],
  },
  {
    slug: 'ud-clinical-summary',
    code: 'UDCS',
    name: 'UD Clinical Summary',
    description: 'Convert clinical notes into structured, sealed patient summary documents.',
    url: 'https://utilities.hive.baby/clinical-summary',
    checklist: [
      'Paste a set of clinical notes and generate',
      'Check SOAP format is followed',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with complex multi-problem notes',
      'Test with minimal notes (1-2 sentences)',
      'Check that medical disclaimer is present',
      'Check metadata fields are populated',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-document-intelligence',
    code: 'UDDI',
    name: 'UD Document Intelligence',
    description: 'Extract structured data from any document and output as a validated Universal Document.',
    url: 'https://utilities.hive.baby/document-intelligence',
    checklist: [
      'Upload a form or structured document',
      'Check that fields are extracted correctly',
      'Check that tables are preserved',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Try a scanned document',
      'Try a handwritten note (if supported)',
      'Test with multilingual content',
      'Check AI accuracy rating',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-summarise',
    code: 'UDSUM',
    name: 'UD Summarise',
    description: 'AI-powered document summarisation that outputs a sealed summary as a Universal Document.',
    url: 'https://utilities.hive.baby/summarise',
    checklist: [
      'Upload a long document and summarise',
      'Check summary length is appropriate',
      'Check key points are captured',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with a very short document',
      'Test with a document in another language',
      'Check metadata includes source reference',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-classify',
    code: 'UDCLS',
    name: 'UD Classify',
    description: 'Automatically classify documents by type, sensitivity, and audience.',
    url: 'https://utilities.hive.baby/classify',
    checklist: [
      'Upload a medical document — classified correctly?',
      'Upload a legal document — classified correctly?',
      'Upload a financial document — classified correctly?',
      'Upload a personal letter — classified correctly?',
      'Check sensitivity level is appropriate',
      'Check audience classification makes sense',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Test with an ambiguous document',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-accessibility-check',
    code: 'UDAC',
    name: 'UD Accessibility Check',
    description: 'Audit Universal Documents for accessibility compliance and generate a remediation report.',
    url: 'https://utilities.hive.baby/accessibility-check',
    checklist: [
      'Upload a document and run accessibility check',
      'Check that issues are described clearly',
      'Check that remediation suggestions are actionable',
      'Test with a well-structured document — should have few issues',
      'Test with a poorly structured document — should flag many issues',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Check that severity levels are assigned',
      'Test on mobile',
      'Download report and re-open — consistent?',
    ],
  },
  {
    slug: 'ud-watermark',
    code: 'UDWM',
    name: 'UD Watermark',
    description: 'Apply invisible cryptographic watermarks to Universal Documents for tracking and provenance.',
    url: 'https://utilities.hive.baby/watermark',
    checklist: [
      'Apply a watermark to a .uds file',
      'Check watermark metadata is embedded',
      'Open watermarked file in UD Reader',
      'Validate in UD Validator',
      'Try applying watermark twice — handled correctly?',
      'Check chain of custody updated',
      'Verify watermark data is readable from metadata',
      'Test with a large document',
      'Test on mobile',
      'Download and re-verify — consistent?',
    ],
  },
  {
    slug: 'ud-compare',
    code: 'UDCMP',
    name: 'UD Compare',
    description: 'Compare two Universal Documents and generate a diff report showing all changes.',
    url: 'https://utilities.hive.baby/compare',
    checklist: [
      'Compare two identical documents — reports no changes',
      'Compare two similar documents — differences shown clearly',
      'Compare original and translated versions',
      'Check that added blocks are highlighted',
      'Check that deleted blocks are highlighted',
      'Check that modified blocks show before/after',
      'Open diff report in UD Reader',
      'Validate diff report in UD Validator',
      'Test with large documents',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-merge',
    code: 'UDMRG',
    name: 'UD Merge',
    description: 'Merge multiple Universal Documents into a single consolidated document.',
    url: 'https://utilities.hive.baby/merge',
    checklist: [
      'Merge two documents — output is a combined document',
      'Check that all blocks from both documents appear',
      'Check that metadata is merged correctly',
      'Open merged file in UD Reader',
      'Validate in UD Validator',
      'Merge three or more documents',
      'Merge documents in different languages',
      'Check chain of custody includes merge event',
      'Test with large documents',
      'Test on mobile',
    ],
  },
  {
    slug: 'ud-ocr',
    code: 'UDOCR',
    name: 'UD OCR',
    description: 'Extract text from scanned documents and images and output as Universal Documents.',
    url: 'https://utilities.hive.baby/ocr',
    checklist: [
      'Upload a scanned PDF — text extracted correctly?',
      'Upload a photo of a document — text extracted?',
      'Check accuracy of extracted text',
      'Check that layout is preserved where possible',
      'Open output in UD Reader',
      'Validate in UD Validator',
      'Try a low-quality scan — graceful handling?',
      'Try a multilingual document',
      'Test on mobile',
      'Download and re-open — consistent?',
    ],
  },

  // ── Hive Engines ──────────────────────────────────────────────
  {
    slug: 'hivephoto',
    code: 'HPHT',
    name: 'HivePhoto',
    description: 'AI-powered private photo library with smart search, face recognition, and duplicate detection.',
    url: 'https://hivephoto.hive.baby',
    checklist: [
      'Sign up and confirm email arrives in under 2 minutes',
      'Upload 3 photos from different dates',
      'Upload the same photo twice — does duplicate detection catch it?',
      'Try the search: "show me photos with people"',
      'Check the GPS map view accuracy',
      'Try the search: "show me happy photos"',
      'Rate the AI analysis accuracy for one photo',
      'Test face grouping — are faces correctly grouped?',
      'Download a photo at original quality',
      'Test the full UI on mobile layout',
    ],
  },
  {
    slug: 'hiveclock',
    code: 'HCLK',
    name: 'HiveClock',
    description: 'AI-powered time zone intelligence and scheduling assistant for global teams.',
    url: 'https://hiveclock.hive.baby',
    checklist: [
      'Enter a city name — does it resolve to the correct time zone?',
      'Convert a time across 3+ time zones simultaneously',
      'Check that daylight saving transitions are handled correctly',
      'Find the best meeting time for participants in 4 different zones',
      'Test natural language input: "9am Tokyo in New York"',
      'Check the AI scheduling suggestion quality',
      'Test with a city that has a non-standard UTC offset (e.g. Kathmandu +5:45)',
      'Verify the clock display updates in real time',
      'Test on mobile — layout correct?',
      'Export meeting time as a calendar event',
    ],
  },
  {
    slug: 'hiveclarity',
    code: 'HCLY',
    name: 'HiveClarity',
    description: 'AI-powered communication clarity engine — rewrites unclear messages with precision and confidence.',
    url: 'https://hiveclarity.hive.baby',
    checklist: [
      'Paste a vague or passive message — does the rewrite improve clarity?',
      'Test with a sensitive workplace message (feedback, disagreement)',
      'Test with an emotional personal message',
      'Test with a technical explanation that needs simplifying',
      'Check that the tone is preserved in rewrites',
      'Test the "make it shorter" option',
      'Test the "make it more assertive" option',
      'Test with a non-English input — is it handled gracefully?',
      'Copy output — does it paste cleanly?',
      'Test on mobile — input and output both usable?',
    ],
  },
  {
    slug: 'hivestrength',
    code: 'HSTR',
    name: 'HiveStrength',
    description: 'AI strength and conditioning coach — personalised training plans and plateau-breaking protocols.',
    url: 'https://hivestrength.hive.baby',
    checklist: [
      'Enter your current lifts and get a training programme',
      'Describe a plateau — does the AI give a specific protocol?',
      'Test with a beginner profile — is advice appropriate?',
      'Test with an advanced lifter — is advice appropriately advanced?',
      'Ask about injury modification for a common issue (e.g. bad knees)',
      'Check that progressive overload is built into any programme',
      'Ask for a deload week recommendation',
      'Test the auto-demo on first visit',
      'Test on mobile — input fields usable?',
      'Check health disclaimer is present',
    ],
  },
  {
    slug: 'hivefield',
    code: 'HFLD',
    name: 'HiveField',
    description: 'AI clinical scenario engine for healthcare training — real-time decision support under pressure.',
    url: 'https://hivefield.hive.baby',
    checklist: [
      'Enter a clinical scenario and check the AI response is realistic',
      'Test with an acute emergency scenario (e.g. chest pain)',
      'Test with a chronic disease management scenario',
      'Test with a paediatric case',
      'Check that responses include appropriate differentials',
      'Check that safety-critical steps are not omitted',
      'Verify that the medical disclaimer is visible',
      'Test the auto-demo on first visit',
      'Test with a very brief scenario — does it ask for more detail?',
      'Test on mobile — readable output?',
    ],
  },
  {
    slug: 'hivebodylog',
    code: 'HBDL',
    name: 'HiveBodyLog',
    description: 'AI symptom and body log — track patterns, spot trends, and get a GP-ready summary.',
    url: 'https://hivebodylog.hive.baby',
    checklist: [
      'Log a symptom with date, time, and severity',
      'Log the same symptom on 3 consecutive days',
      'Check that the trend analysis identifies the pattern',
      'Generate a GP-ready summary — is it accurate?',
      'Test the auto-demo on first visit',
      'Log a symptom with associated factors (food, sleep, stress)',
      'Check that the AI flags any concerning patterns',
      'Export the log — does the file download correctly?',
      'Check that medical disclaimer is visible',
      'Test on mobile — logging flow is smooth?',
    ],
  },
  {
    slug: 'hivesecretbox',
    code: 'HSBX',
    name: 'HiveSecretBox',
    description: 'Zero-knowledge encrypted secret storage — your secrets never leave your browser unencrypted.',
    url: 'https://secretbox.hive.baby',
    checklist: [
      'Create a new secret with a passphrase',
      'Retrieve the secret using the correct passphrase',
      'Try the wrong passphrase — is access correctly denied?',
      'Check that the secret is not visible in browser storage unencrypted',
      'Share a secret link — does the recipient see it correctly?',
      'Check that a shared secret link expires or single-uses as designed',
      'Test with a very long secret (1000+ characters)',
      'Test with special characters and emoji in the secret',
      'Test on mobile',
      'Check that no data is sent to the server unencrypted',
    ],
  },
  {
    slug: 'whotextedme',
    code: 'WHTM',
    name: 'WhoTextedMe',
    description: 'AI text message analyser — paste any message and get a clear, honest read on tone and intent.',
    url: 'https://whotextedme.hive.baby',
    checklist: [
      'Paste an ambiguous text — does the AI give a useful analysis?',
      'Test with a clearly positive message — labelled correctly?',
      'Test with a passive-aggressive message — is it identified?',
      'Test with a ghosting or avoidant response',
      'Test with a very short message (e.g. "k")',
      'Test with a long multi-paragraph message',
      'Check that the analysis is empathetic not dismissive',
      'Test with a non-English message',
      'Test on mobile — input usable?',
      'Copy analysis output — pastes cleanly?',
    ],
  },
  {
    slug: 'hiveaestheticbestie',
    code: 'HAES',
    name: 'HiveAestheticBestie',
    description: 'AI aesthetic and style advisor — honest feedback on outfits, rooms, and creative decisions.',
    url: 'https://hiveaestheticbestie.hive.baby',
    checklist: [
      'Upload a photo and ask for style feedback',
      'Ask about a colour combination — is the response specific?',
      'Test with a room interior — does it give actionable feedback?',
      'Test with an outfit photo',
      'Ask for a style direction based on a mood or occasion',
      'Check the feedback is honest, not just flattering',
      'Test with a low-quality image — graceful handling?',
      'Test without an image (text-only query)',
      'Test on mobile — upload works from camera roll?',
      'Check that no image is stored after the session',
    ],
  },
  {
    slug: 'hivemicroritual',
    code: 'HMRT',
    name: 'HiveMicroRitual',
    description: 'AI-powered micro habit and ritual builder — tiny daily practices with outsized impact.',
    url: 'https://hivemicroritual.hive.baby',
    checklist: [
      'Describe a goal and get a set of micro rituals',
      'Test with a stress-reduction goal',
      'Test with a productivity goal',
      'Test with a health goal (sleep, movement, food)',
      'Check that rituals are genuinely "micro" (under 5 minutes)',
      'Ask for a morning routine — is it realistic?',
      'Ask for an evening wind-down routine',
      'Test the auto-demo on first visit',
      'Save or export a ritual set — works correctly?',
      'Test on mobile — readable and usable?',
    ],
  },
  {
    slug: 'sovereignarbitrage',
    code: 'SARB',
    name: 'SovereignArbitrage',
    description: 'AI-powered sovereign finance and arbitrage intelligence — flag-planting, residency, and asset strategy.',
    url: 'https://sovereignarbitrage.hive.baby',
    checklist: [
      'Enter a nationality + goal and get a strategy overview',
      'Ask about tax residency options for a specific country',
      'Ask about second residency or citizenship by investment',
      'Check that responses cite relevant jurisdictions specifically',
      'Ask about currency diversification strategies',
      'Check that legal disclaimers are present',
      'Test with an edge-case nationality (e.g. sanctioned country)',
      'Ask a follow-up question — does context carry?',
      'Test on mobile — layout correct?',
      'Check that the AI does not give specific legal or tax advice without disclaimer',
    ],
  },
  {
    slug: 'imgtrainer',
    code: 'IMGT',
    name: 'IMGTrainer',
    description: 'Clinical reasoning trainer for international medical graduates preparing for USMLE Step 2 CK. Chat with a simulated patient, order workup, get structured feedback.',
    url: 'https://imgtrainer.hive.baby',
    checklist: [
      'Sign up with a fresh email — welcome email arrives within 10 seconds',
      'Click "Start your first case free" — lands on the case page (chest pain, 58M)',
      'Ask the patient 3-4 questions — replies stream in token-by-token in character',
      'Order an ECG and a troponin — results appear inline with timestamps',
      'Try ordering a D-dimer or CT-PA — deliberation prompt appears with Cancel / Order anyway',
      'Submit a differential and plan — full-screen overlay shows cycling status messages',
      'Grading screen renders with overall score, five rubric cards, and a Step 2 practice question',
      'Results email arrives at the signup address with score and takeaway',
      'After 2 free cases, navigating to /case/chest-pain-58m redirects to /account?paywall=true',
      'Subscribe with Stripe test card 4242 4242 4242 4242 — receipt email arrives, plan flips to paid',
    ],
  },
]

export function getEngineBySlug(slug: string): Engine | undefined {
  return ENGINES.find(e => e.slug === slug)
}

export function getEngineByCode(code: string): Engine | undefined {
  return ENGINES.find(e => e.code === code)
}
